version: '3'
services:
  prisma-mysql:
    image: mysql:latest
    container_name: prisma-mysql-container-dev
    environment:
      MYSQL_ROOT_PASSWORD: LdsfgjpmLDSFg8941sdfgsdfcc
      MYSQL_DATABASE: mysql-image-database
    ports:
      - '3306:3306'
  prisma-redis:
    image: redis:latest
    container_name: prisma-redis-container-dev
    environment:
      REDIS_PASSWORD: qsdfsqjklhqo6q4sfFGHazf5464  
    ports:
      - '6379:6379'